-- Create Address_Type table
CREATE TABLE Address_Type (
 address_id NUMBER(2) PRIMARY KEY,
address_type VARCHAR2(20) NOT NULL,
address_desc CLOB
);
-- Create Employee_Type table
CREATE TABLE Employee_Type (
 employee_type_id NUMBER GENERATED BY DEFAULT ON NULL AS
IDENTITY PRIMARY KEY,
 employee_type VARCHAR2(30),
 employee_type_desc CLOB,
 pay_type VARCHAR2(10),
 compensation_package NUMBER(12,2)
);
-- Create Employee_Role table
CREATE TABLE Employee_Role (
 employee_role_id NUMBER PRIMARY KEY,
 role_name VARCHAR2(50) NOT NULL,
 role_desc CLOB
);
-- Create Organization table
CREATE TABLE Organization (
 organization_id NUMBER PRIMARY KEY,
 org_name VARCHAR2(50) NOT NULL,
 commence_date DATE,
 address CLOB,
 country_code VARCHAR2(20)
);
-- Create Employee table
CREATE TABLE Employee (
 employee_id NUMBER PRIMARY KEY,
 employee_name VARCHAR2(30) NOT NULL,
 employee_type_id NUMBER NOT NULL,
 employee_role_id NUMBER NOT NULL,
 organization_id NUMBER NOT NULL,
 date_of_birth DATE NOT NULL,
 date_of_joining DATE NOT NULL,
 salary NUMBER(10, 2) NOT NULL,
address CLOB NOT NULL,
address_id NUMBER,
 home_country VARCHAR2(30) NOT NULL,
 work_country VARCHAR2(30) NOT NULL,
 gender CHAR(1) CHECK (gender IN ('M', 'F')) NOT NULL,
 marital_status VARCHAR2(20) NOT NULL,
 ethnicity VARCHAR2(30) NOT NULL,
 CONSTRAINT fk_employee_type FOREIGN KEY (employee_type_id)
REFERENCES Employee_Type(employee_type_id),
 CONSTRAINT fk_employee_role FOREIGN KEY (employee_role_id)
REFERENCES Employee_Role(employee_role_id),
CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES
Organization(organization_id),
CONSTRAINT fk_address_id FOREIGN KEY (address_id) REFERENCES
Address_Type(address_id)
);